/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_emery_ffmpeg_VideoPlayer */

#ifndef _Included_com_example_emery_ffmpeg_VideoPlayer
#define _Included_com_example_emery_ffmpeg_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_emery_ffmpeg_VideoPlayer
 * Method:    convertYuv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_emery_ffmpeg_VideoPlayer_convertYuv
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
