/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_emery_ffmpeg_AudioPlayer */

#ifndef _Included_com_example_emery_ffmpeg_AudioPlayer
#define _Included_com_example_emery_ffmpeg_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_emery_ffmpeg_AudioPlayer
 * Method:    convertPCM
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_emery_ffmpeg_AudioPlayer_convertPCM
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_emery_ffmpeg_AudioPlayer
 * Method:    directPlay
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_emery_ffmpeg_AudioPlayer_directPlay
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
