/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_emery_ffmpeg_EmeryPlayer */

#ifndef _Included_com_example_emery_ffmpeg_EmeryPlayer
#define _Included_com_example_emery_ffmpeg_EmeryPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_emery_ffmpeg_EmeryPlayer
 * Method:    audioVideoPlay
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_emery_ffmpeg_EmeryPlayer_audioVideoPlay
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
